# Generated by Django 5.0 on 2023-12-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='transaction_ref',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
