# Generated by Django 5.0 on 2023-12-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_transactionhistory_transaction_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='currency',
            field=models.CharField(choices=[('btc', 'btc'), ('lth', 'lth'), ('eth', 'eth')], default='btc', max_length=200),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(choices=[('btc', 'btc'), ('lth', 'lth'), ('eth', 'eth')], default='btc', max_length=200),
        ),
    ]
