# Generated by Django 5.0 on 2023-12-27 12:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transactionhistory_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wallet',
            new_name='UserWallet',
        ),
    ]
