# Generated by Django 5.0 on 2023-12-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_wallet_userwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='balance',
            field=models.FloatField(),
        ),
    ]
