# Generated by Django 5.0 on 2023-12-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_transactionhistory_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='address',
            field=models.CharField(max_length=50),
        ),
    ]
