# Generated by Django 5.0 on 2024-01-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_transactionhistory_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='wallet',
        ),
    ]
