# Generated by Django 5.0 on 2024-01-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_transactionhistory_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionhistory',
            old_name='address',
            new_name='from_address',
        ),
        migrations.AddField(
            model_name='transactionhistory',
            name='to_address',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
